FROM python:3.6 AS builder

ENV PATH=/root/.local/bin:$PATH

COPY requirements.txt .
RUN pip install --user -r requirements.txt

FROM python:3.6-slim

WORKDIR /app
COPY --from=builder /root/.local/bin/ /root/.local
COPY ./proxy .

EXPOSE 5000
CMD ["python3", "-m", "proxy"]

